# Generated by Django 2.1.1 on 2018-09-17 04:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('blog', models.CharField(max_length=200, null=True)),
                ('public_posts', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('followers', models.IntegerField(null=True)),
                ('following', models.IntegerField(null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2018, 9, 17, 9, 55, 38, 196979))),
                ('location', models.CharField(max_length=100, null=True)),
                ('avatar', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
