# Generated by Django 2.1.1 on 2018-09-17 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 17, 11, 7, 56, 909420)),
        ),
    ]
